require('lazy-c')
require('opts')
require('maps')
require('style')
require('coq-c')
require('lsp-c')
require('monokai-c')
require('supertab-c')
require('treesitter-c')

-- require('coqConfig')
-- require('tokyonightConfig')
-- require('styleconfig')
-- require('lspConfig')
-- require('treesitterConfig')
-- require('autopairsConfig')
-- require('supertabconfig')
-- require('monokaiproConfig')
