return {
	"folke/tokyonight.nvim",
	"maxmx03/solarized.nvim",
	"catppuccin/nvim",
	"tpope/vim-abolish",
	"tpope/vim-surround",
	"tpope/vim-commentary",
	"fatih/vim-go",
	"sebdah/vim-delve",
	"MaxMEllon/vim-jsx-pretty",
	"sindrets/diffview.nvim",
	"f-person/git-blame.nvim",
	"sainnhe/everforest",
	"tpope/vim-fugitive",
	"kamykn/spelunker.vim",
}
